database:
  url: "jdbc:mysql://localhost:3306/openmccore"
  user: "root"
  password: "password"
rtp:
  cooldown: 60
  cooldown-error: 5
  minx: -3000
  maxx: 3000
  minz: -3000
  maxz: 3000
  rtp_wand: "wand:rtpwand"
  max_try: 3
spawn:
  x: 5611.5
  y: 65.0
  z: 1226.5
  world: world
deco_freeze_nombre_de_jours_ban: 30
discord:
  webhookURL: https://discord.com/api/webhooks/1258553652868677802/u17NMB93chQrYf6V0MnbKPMbjoY6B_jN9e2nhK__uU8poc-d8a-aqaT_C0_ur4TSFMy_
  webhookIconURL: https://media.discordapp.net/attachments/1161296445169741836/1258408047412383804/image.png?ex=66889812&is=66874692&hm=4bb38f7b6460952afc21811f7145a6b289d7210861d81d91b1ca8ee264f0ab0d&=&format=webp&quality=lossless&width=1131&height=662
  webhookName: Annonce Serveur
mine:
  name: mine

rewards:
  peluche_aywen: #Example à laisser
    start: 1722636000 # Date de début de l'event
    end: 1725832800 # Date de fin de l'event
    reward: "aywen:peluche" # Namespace ItemsAdder